import { readFile, writeFile } from 'node:fs/promises';

const stripModules = (source) => source
  .replace(/^import .*;\r?\n/gm, '')
  .replace(/\bexport\s+(?=(const|function|class)\b)/g, '');

const files = [
  './src/engine.js',
  './src/law-packs/cn-mainland-2021.js',
  './src/solver.js',
  './src/storm-solver.js',
  './src/app.js'
];
const parts = await Promise.all(files.map(async (file) => stripModules(await readFile(file, 'utf8'))));
const bundle = `/* Generated by build.mjs. Edit files in src/, then run npm run build. */\n(() => {\n${parts.join('\n\n')}\n})();\n`;
await writeFile('./bundle.js', bundle);
console.log('Built bundle.js');
